import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const zen_kaku_gothic_new = Zen_Kaku_Gothic_New({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={zen_kaku_gothic_new.className}>{children}</body>
    </html>
  );
}
